Repository CS2103-AY1819S2-W17-1/main, pull requests merged in 2019-04, with the labels that each got.

#94 Fix GUI bugs and add tests for Review GUI
  src/main/java/seedu/address/logic/commands/AddReviewCommand.java
  src/main/java/seedu/address/logic/commands/DeleteReviewCommand.java
  src/main/java/seedu/address/logic/commands/EditReviewCommand.java
  src/main/java/seedu/address/ui/ReviewCard.java
  src/main/java/seedu/address/ui/ReviewListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/RestaurantListCard.fxml
  src/main/resources/view/RestaurantListPanel.fxml
  src/main/resources/view/ReviewListCard.fxml
  src/main/resources/view/ReviewListPanel.fxml
  src/main/resources/view/default.html
  src/main/resources/view/seguisb.ttf
  src/test/java/guitests/guihandles/ReviewCardHandle.java
  src/test/java/guitests/guihandles/ReviewListPanelHandle.java
  src/test/java/seedu/address/testutil/RestaurantBuilder.java
  src/test/java/seedu/address/testutil/TypicalReviews.java
  src/test/java/seedu/address/ui/ReviewCardTest.java
  src/test/java/seedu/address/ui/ReviewListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
Labels: priority.Medium, severity.Medium, status.ReadyForReview, type.Bug

#96 Enhanced visit web
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/exceptions/NoInternetException.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/VisitWebCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/VisitWebCommandParser.java
  src/main/java/seedu/address/model/restaurant/Weblink.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.Medium, status.ReadyForReview, type.Enhancement

#103 Create RestaurantSummary and display it in the GUI
  src/main/java/seedu/address/model/restaurant/Restaurant.java
  src/main/java/seedu/address/model/restaurant/Summary.java
  src/main/java/seedu/address/model/review/Rating.java
  src/main/java/seedu/address/model/review/Review.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RestaurantCard.java
  src/main/java/seedu/address/ui/RestaurantSummaryDisplay.java
  src/main/java/seedu/address/ui/RestaurantSummaryPanel.java
  src/main/java/seedu/address/ui/ReviewCard.java
  src/main/java/seedu/address/ui/ReviewListPanel.java
  src/main/resources/images/star.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/RestaurantListCard.fxml
  src/main/resources/view/RestaurantSummaryDisplay.fxml
  src/main/resources/view/RestaurantSummaryPanel.fxml
Labels: priority.Medium, severity.Low, status.Ongoing, status.ReadyForReview, type.Enhancement

#102 fixed editReview commands bug of not being able to edit the first index
  src/main/java/seedu/address/logic/commands/EditReviewCommand.java
Labels: priority.High, severity.High, status.ReadyForReview, type.Bug

#98 Restaurant categorisation 1.3
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/SetCategoriesActivityDiagram.pptx
  docs/diagrams/SetCategoriesSequenceDiagram.pptx
  docs/images/SetCategoriesActivityDiagram.png
  docs/images/SetCategoriesSequenceDiagram.png
  docs/team/rbth7e5.adoc
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/SetCategoriesCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/FoodDiaryParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SetCategoriesCommandParser.java
  src/main/java/seedu/address/model/restaurant/Restaurant.java
  src/main/java/seedu/address/model/restaurant/categories/Categories.java
  src/main/java/seedu/address/model/restaurant/categories/CategoriesContainKeywordsPredicate.java
  src/main/java/seedu/address/model/restaurant/categories/Category.java
  src/main/java/seedu/address/model/restaurant/categories/CategoryContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/restaurant/categories/Cuisine.java
  src/main/java/seedu/address/model/restaurant/categories/Occasion.java
  src/main/java/seedu/address/model/restaurant/categories/PriceRange.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedCategories.java
  src/main/java/seedu/address/storage/JsonAdaptedRestaurant.java
  src/main/java/seedu/address/ui/RestaurantCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/RestaurantListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/SetCategoriesCommandTest.java
  src/test/java/seedu/address/logic/parser/SetCategoriesCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedRestaurantTest.java
  src/test/java/seedu/address/testutil/RestaurantBuilder.java
Labels: status.ReadyForReview

#112 Fix summary panel UI bugs and reviews and setCategories bug
  src/main/java/seedu/address/logic/commands/DeleteReviewCommand.java
  src/main/java/seedu/address/logic/commands/EditReviewCommand.java
  src/main/java/seedu/address/model/restaurant/Restaurant.java
  src/main/java/seedu/address/ui/RestaurantSummaryDisplay.java
  src/main/java/seedu/address/ui/RestaurantSummaryPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/RestaurantSummaryDisplay.fxml
  src/main/resources/view/RestaurantSummaryPanel.fxml
Labels: priority.High, severity.High, status.ReadyForReview, type.Bug

#116 Docs Update
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/rbth7e5.adoc
Labels: severity.Low, status.ReadyForReview

#115 Fix bug for no internet validation
  docs/DeveloperGuide.adoc
  docs/images/VisitWebUrlActivityDiagram.png
  docs/images/visitWebUrlActivity.png
  docs/team/wklee96.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/exceptions/NoInternetException.java
  src/main/java/seedu/address/commons/util/WebUtil.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/VisitWebCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/VisitWebCommandParser.java
  src/main/java/seedu/address/model/restaurant/Weblink.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/RestaurantCard.java
  src/main/java/seedu/address/ui/RestaurantSummaryPanel.java
Labels: status.ReadyForReview, type.Bug

#113 Fix regex for Ratings to allow leading 0s and edit documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/SelectActivityDiagram.pptx
  docs/diagrams/SelectSequenceDiagram.pptx
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/ModelClassDiagramV1.3.png
  docs/images/SelectActivityDiagram.png
  docs/images/SelectSequenceDiagram.png
  docs/images/UiClassDiagramV1.3.png
  docs/images/UiUpdated.png
  docs/images/selectafter.png
  docs/images/selectbefore.png
  docs/team/weixin-koh.adoc
  src/main/java/seedu/address/model/review/Rating.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/RestaurantSummaryPanel.fxml
Labels: priority.High, severity.Medium, status.Ongoing, type.Bug

#118 Fix bugs and update documentation
  docs/UserGuide.adoc
  docs/diagrams/LogicComponentClassDiagram.pptx
  docs/diagrams/LogicComponentSequenceDiagram.pptx
  docs/diagrams/SelectActivityDiagram.pptx
  docs/diagrams/SelectSequenceDiagram.pptx
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/diagrams/UndoRedoActivityDiagram.pptx
  docs/diagrams/UndoRedoExecuteUndoStateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand1StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand2StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand3StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand4StateListDiagram.pptx
  docs/diagrams/UndoRedoStartingStateListDiagram.pptx
  docs/images/LogicClassDiagram.png
  docs/images/SDforDeleteRestaurant.png
  docs/images/SelectActivityDiagram.png
  docs/images/SelectSequenceDiagram.png
  docs/images/StorageClassDiagramV1.2.png
  docs/images/UndoRedoActivityDiagram.png
  docs/images/UndoRedoExecuteUndoStateListDiagram.png
  docs/images/UndoRedoNewCommand1StateListDiagram.png
  docs/images/UndoRedoNewCommand2StateListDiagram.png
  docs/images/UndoRedoNewCommand3StateListDiagram.png
  docs/images/UndoRedoNewCommand4StateListDiagram.png
  docs/images/UndoRedoStartingStateListDiagram.png
  docs/team/weixin-koh.adoc
  src/main/java/seedu/address/ui/ReviewListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ReviewListCard.fxml
  src/test/java/guitests/guihandles/ReviewCardHandle.java
Labels: priority.High, severity.Low, status.ReadyForReview, type.Bug, type.Task

#141 allow edit of only openinghours field
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: status.ReadyForReview, type.Bug

#140 Autocomplete for categories
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/SetCategoriesSequenceDiagram.pptx
  docs/images/SetCategoriesActivityDiagram.png
  docs/images/SetCategoriesSequenceDiagram.png
  docs/images/setcategories-stepfive.png
  docs/images/setcategories-stepfour.png
  docs/images/setcategories-stepone.png
  docs/images/setcategories-stepthree.png
  docs/images/setcategories-steptwo.png
  docs/team/rbth7e5.adoc
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/model/restaurant/categories/Categories.java
  src/main/java/seedu/address/model/restaurant/categories/Cuisine.java
  src/main/java/seedu/address/model/restaurant/categories/Occasion.java
  src/main/java/seedu/address/model/restaurant/categories/PriceRange.java
  src/main/java/seedu/address/ui/CategoriesAutoCompleteTextField.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/resources/view/CommandBox.fxml
Labels: priority.Medium, severity.Low, status.Ongoing

#142 Browser window
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/UiClassDiagramV1.3.png
  docs/images/VisitWebUrlActivityDiagram.png
  src/main/java/seedu/address/commons/util/WebUtil.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/VisitWebCommand.java
  src/main/java/seedu/address/model/restaurant/OpeningHours.java
  src/main/java/seedu/address/model/restaurant/Weblink.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RestaurantCard.java
  src/main/resources/view/BrowserPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/guitests/GuiRobot.java
  src/test/java/guitests/guihandles/BrowserPanelHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/systemtests/FoodDiarySystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: severity.High, status.ReadyForReview, type.Bug

#144 updated docs and implementation of certain classes
  README.adoc
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/commands/ListUnvisitedCommand.java
  src/main/java/seedu/address/logic/commands/comparators/SortDistanceComparator.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/storage/JsonSerializablePostalData.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RestaurantCard.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/view/RestaurantListCard.fxml
  src/test/java/seedu/address/logic/commands/ListUnvisitedCommandTest.java
  src/test/java/seedu/address/ui/StatusBarFooterTest.java
Labels: priority.Medium, status.ReadyForReview

#148 Implement Sort Command to sort Restaurants by Ratings and fix selection of added/edited/deleted Reviews
  src/main/java/seedu/address/logic/commands/AddReviewCommand.java
  src/main/java/seedu/address/logic/commands/DeleteReviewCommand.java
  src/main/java/seedu/address/logic/commands/EditReviewCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/commands/comparators/SortName.java
  src/main/java/seedu/address/logic/commands/comparators/SortRating.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FoodDiaryParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/FoodDiary.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/restaurant/Summary.java
  src/main/java/seedu/address/model/restaurant/UniqueRestaurantList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.Medium, status.Ongoing, type.Enhancement, type.Story

#152 Made Phone and Email fields of restaurant Optional
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/restaurant/Email.java
  src/main/java/seedu/address/model/restaurant/OpeningHours.java
  src/main/java/seedu/address/model/restaurant/Phone.java
  src/main/java/seedu/address/model/restaurant/Restaurant.java
  src/main/java/seedu/address/model/restaurant/Weblink.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RestaurantCard.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: status.ReadyForReview, type.Enhancement

#150 Modified implementation of WebUtil methods
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/VisitWebSequenceDiagram.pptx
  docs/images/InvalidWeblink.PNG
  docs/images/InvalidWeblinkEdit.PNG
  docs/images/NoInternetAdd.PNG
  docs/images/NoInternetEdit.PNG
  docs/images/VisitWebSequenceDiagram.png
  docs/images/VisitWebUrlActivityDiagram.png
  docs/images/VisitWebUrlSequenceDiagram.png
  docs/images/visitWeb.PNG
  docs/images/visitWebJolliB.PNG
  docs/team/wklee96.adoc
  src/main/java/seedu/address/commons/util/WebUtil.java
  src/main/java/seedu/address/logic/commands/VisitWebCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/VisitWebCommandParser.java
  src/main/java/seedu/address/model/restaurant/OpeningHours.java
  src/main/java/seedu/address/model/restaurant/Weblink.java
  src/main/java/seedu/address/storage/JsonAdaptedRestaurant.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/RestaurantCard.java
  src/main/java/seedu/address/ui/RestaurantSummaryPanel.java
  src/test/data/JsonSerializableFoodDiaryTest/typicalRestaurantsFoodDiary.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/VisitWebCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/VisitWebCommandParserTest.java
  src/test/java/seedu/address/model/restaurant/OpeningHoursTest.java
  src/test/java/seedu/address/model/restaurant/WeblinkTest.java
  src/test/java/seedu/address/testutil/RestaurantBuilder.java
  src/test/java/seedu/address/testutil/TypicalRestaurants.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: priority.Low, status.Ongoing, type.Enhancement

#153 Tests
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/SetCategoriesActivityDiagram.pptx
  docs/images/SetCategoriesActivityDiagram.png
  docs/stylesheets/gh-pages.css
  docs/team/rbth7e5.adoc
  src/main/java/seedu/address/logic/commands/SetCategoriesCommand.java
  src/main/java/seedu/address/ui/CategoriesAutoCompleteTextField.java
  src/test/java/guitests/guihandles/CommandBoxHandle.java
  src/test/java/seedu/address/logic/commands/SetCategoriesCommandTest.java
  src/test/java/seedu/address/model/restaurant/categories/CategoriesTest.java
  src/test/java/seedu/address/model/restaurant/categories/OccasionTest.java
  src/test/java/seedu/address/model/restaurant/categories/PriceRangeTest.java
  src/test/java/seedu/address/testutil/RestaurantBuilder.java
  src/test/java/seedu/address/testutil/TypicalCategories.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
Labels: severity.Low, status.ReadyForReview, type.Task

#160 V1.4
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/images/ListUnvisitedLogicActivityDiagram.png
  docs/images/ListUnvisitedSequenceDiagram.png
  docs/team/chanqingzhou.adoc
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListUnvisitedCommand.java
  src/main/java/seedu/address/logic/commands/comparators/SortDistanceComparator.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/PostalData.java
  src/main/java/seedu/address/model/PostalDataSet.java
  src/main/java/seedu/address/model/restaurant/Postal.java
  src/main/java/seedu/address/model/restaurant/Restaurant.java
  src/test/data/JsonSerializableFoodDiaryTest/typicalRestaurantsFoodDiary.json
  src/test/data/JsonSerializablePostalDataTest/JsonSerializablePostalDataTest
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ListUnvisitedCommandTest.java
  src/test/java/seedu/address/logic/parser/FoodDiaryParserTest.java
  src/test/java/seedu/address/model/restaurant/PostalTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPostalDataTest.java
  src/test/java/seedu/address/testutil/EditRestaurantDescriptorBuilder.java
  src/test/java/seedu/address/testutil/RestaurantUtil.java
  src/test/java/seedu/address/testutil/TypicalPostalData.java
  src/test/java/seedu/address/testutil/TypicalRestaurants.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FoodDiarySystemTest.java
  src/test/java/systemtests/ListUnvisitedCommandSystemTest.java
  src/test/java/systemtests/ModelHelper.java
Labels: priority.Medium, status.ReadyForReview

#165 Added sample data and updated docs.
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/wklee96.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/VisitWebCommand.java
  src/main/java/seedu/address/logic/parser/VisitWebCommandParser.java
  src/main/java/seedu/address/model/restaurant/Weblink.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/guitests/guihandles/RestaurantCardHandle.java
  src/test/java/seedu/address/logic/parser/VisitWebCommandParserTest.java
  src/test/java/seedu/address/model/restaurant/WeblinkTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/ListUnvisitedCommandSystemTest.java
Labels: priority.High, type.Task

#166 Add logos to intro page and PPP
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/thefooddiary.png
  docs/team/rbth7e5.adoc
Labels: priority.Medium, severity.Low, status.Ongoing, type.Task

#169 fix display error
  docs/UserGuide.adoc
Labels: priority.High, severity.Low, status.ReadyForReview, type.Task

#173 Edit DG
  docs/DeveloperGuide.adoc
Labels: type.Task
