Repository CS2103-AY1819S2-W17-1/main, pull requests merged in 2019-03, with the labels that each got.

#66 Updated link for travis on readme
  README.adoc
Labels: type.Bug

#75 DevGuide update: fixed tutor comments on dev guide, added implementation details of addReview command.
  docs/DeveloperGuide.adoc
  docs/images/DeleteRestaurantSdForLogic.png
  docs/images/SDforDeleteRestaurant.png
  src/main/java/seedu/address/logic/commands/AddReviewCommand.java
Labels: status.ReadyForReview

#77 Update Developer Guide and User Guide with updated diagrams and UI mockups
  README.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/ModelClassDiagramV1.2.png
  docs/images/StorageClassDiagramV1.2.png
  docs/images/UiClassDiagramV1.2.png
  docs/images/UiUpdated.png
Labels: status.ReadyForReview

#76 Fix tutor pr comments
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  src/main/java/seedu/address/logic/commands/AddReviewCommand.java
  src/main/java/seedu/address/logic/commands/EditReviewCommand.java
  src/main/java/seedu/address/logic/commands/NameCommand.java
  src/main/java/seedu/address/logic/parser/AddReviewCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditReviewCommandParser.java
  src/main/java/seedu/address/logic/parser/FoodDiaryParser.java
  src/main/java/seedu/address/logic/parser/NameCommandParser.java
  src/main/java/seedu/address/model/restaurant/Restaurant.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/testutil/ReviewUtil.java
Labels: status.ReadyForReview

#83 Add _reposense/config.java file for Reposense & edit User Guide
  .gitignore
  _reposense/config.json
  docs/UserGuide.adoc
Labels: priority.High, status.ReadyForReview, type.Task

#88 Fixes filter bug and update docs
  docs/UserGuide.adoc
  src/main/java/seedu/address/model/restaurant/categories/CategoryContainsKeywordsPredicate.java
Labels: severity.High, status.ReadyForReview
